const Images = {
    food1: require('./food1.jpg'),
    food2: require('./food2.jpeg'),
    food3: require('./food3.jpeg'),
    food4: require('./food4.jpg'),
    food5: require('./food5.jpeg'),
    food6: require('./food6.jpeg'),
    food7: require('./food7.jpg'),
    one: require('./1.jpeg'),
    two: require('./2.jpeg'),
    three: require('./3.jpeg'),
    four: require('./4.jpeg'),
    five: require('./5.jpeg'),
    six: require('./6.jpg'),
    eight: require('./6.jpeg'),
    nine: require('./8.jpg'),
    table: require('./table.jpeg'),
    table3: require('./table3.jpg'),
    man1: require('./man1.avif'),
    man2: require('./man2.jpg'),
    man3: require('./man3.jpeg'),
    man4: require('./man4.jpeg'),
    group: require('./group.jpg'),
    bar1: require('./bar.jpg'),
    bar2: require('./bar2.jpg'),
    bar4: require('./bar2.webp'),
    dining: require('./dining.jpg'),
    preety: require('./preety.jpeg'),
    foodpic: require('./foodpic.jpeg'),
    private: require('./private.avif'),
    error: require('./error.png'),
}
export default Images;